-- 影术家联网版：Supabase 数据结构
-- 可重复执行。只允许登录用户读写自己的研究数据。

create table if not exists public.research_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{"format":1,"values":{}}'::jsonb,
  revision bigint not null default 0,
  device_id text,
  updated_at timestamptz not null default now()
);

create table if not exists public.research_conflicts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text,
  details jsonb not null default '{}'::jsonb,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists research_conflicts_user_created_idx
  on public.research_conflicts (user_id, created_at desc);

alter table public.research_state enable row level security;
alter table public.research_conflicts enable row level security;

drop policy if exists "research_state_select_own" on public.research_state;
create policy "research_state_select_own"
  on public.research_state for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "research_state_insert_own" on public.research_state;
create policy "research_state_insert_own"
  on public.research_state for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "research_state_update_own" on public.research_state;
create policy "research_state_update_own"
  on public.research_state for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "research_state_delete_own" on public.research_state;
create policy "research_state_delete_own"
  on public.research_state for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "research_conflicts_select_own" on public.research_conflicts;
create policy "research_conflicts_select_own"
  on public.research_conflicts for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "research_conflicts_insert_own" on public.research_conflicts;
create policy "research_conflicts_insert_own"
  on public.research_conflicts for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "research_conflicts_update_own" on public.research_conflicts;
create policy "research_conflicts_update_own"
  on public.research_conflicts for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "research_conflicts_delete_own" on public.research_conflicts;
create policy "research_conflicts_delete_own"
  on public.research_conflicts for delete
  to authenticated
  using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.research_state to authenticated;
grant select, insert, update, delete on public.research_conflicts to authenticated;
grant usage, select on sequence public.research_conflicts_id_seq to authenticated;

